### ISSUE TITLE
Horse can't walk on magma.

### ISSUE THREAD

**Issue by Cognizaunce** [michael-somdecerff/Netherite_Horse_Armor_-Fabric-#2]
Bug/Feature Request:
Currently horses do not take damaga from lava, so why should they take damage from magma? This is the one thing that is preventing me from using horses in the nether.

Using 1.16.5 mod version 1.1.0.

P.s. If you do decide to implement this, could you make it so horses won't take magma damage after being sucked in by its bubble collumn. They should take drowing damage, but not magma damage.

**Comment by Cognizaunce** [comment]
PPS. Forgot to thank you for your work on this mod. I use it on my server and everyone enjoys it. Your mod has been greatly appreciated.

**Comment by michael-somdecerff** [comment]
@Cognizaunce This was a bug that has now been fixed. You can download version 1.3.1 off of the curseforge page that will include this change. 
As for the bubble column, normal mobs have their air constantly refilled while within the column, and as such it would rather break that symmetry if horses started drowning while still in it.

**Comment by michael-somdecerff** [comment]
@Cognizaunce I applied the same update to the 1.16 version as well as the 1.17 version. Refer to the edited previous comment for version numbers.
